Use package.json instead of lein-npm
The error `Error: Cannot find module '@cljs-oss/module-deps'` could be
avoided by adding the `@cljs-oss/module-deps` dependency explicitly. But
I didn't find a way to add it to `project.clj` with legal Clojure
syntax. With package.json & yarn it works.